export const stations = [
  { label: 'Voice cloning', title: 'A voice that is yours.', text: 'Build a reusable voice reference from a clean timeline clip, bin asset or imported recording. Keep your sound ready for the next story.', detail: 'Your reference. Your creative identity.', lines: ['Capture a clean reference', 'Name and save your voice', 'Use it across new takes'], type: 'voice' },
  { label: 'Speech to speech', title: 'Keep the performance. Change the voice.', text: 'Transform a recorded performance using a saved voice. Start with a clip, imported audio or a microphone take, then preview the result.', detail: 'From your original performance to a new take.', lines: ['Select a source performance', 'Choose a saved voice', 'Preview the converted take'], type: 'convert' },
  { label: 'Text to speech', title: 'Give your words a voice.', text: 'Turn an English script into narration with a saved voice. Create takes for films, explainers, lessons and the stories you have yet to tell.', detail: 'English voice generation with your saved references.', lines: ['Write your narration', 'Choose the voice for your story', 'Generate and save a take'], type: 'script' },
  { label: 'Audio repair', title: 'Let the story come through.', text: 'Reduce background noise locally. Separate vocals and accompaniment into clear stems, then listen before bringing the result into your cut.', detail: 'Clean voice, clear music and ready stems.', lines: ['Reduce background noise', 'Separate vocals and music', 'Preview the repaired audio'], type: 'repair' },
  { label: 'Timeline handoff', title: 'Right where your story happens.', text: 'Send a take to the project bin, insert it at the playhead or apply it to the captured source clip. The original audio is preserved in the undo workflow.', detail: 'Designed for editor-first voice production on Windows.', lines: ['Import into your project bin', 'Insert at the playhead', 'Apply to the captured source clip'], type: 'timeline' },
  { label: 'Voices & takes', title: 'Every take. Within reach.', text: 'Preview and name your voice references, keep generated takes with timing information and follow queued jobs as your project takes shape.', detail: 'Your voices, your takes, your next creative direction.', lines: ['Organize saved voice references', 'Keep and preview generated takes', 'Track jobs or cancel a take'], type: 'library' },
];
export const stationProgress = (index: number) => .52 + index * .08;
